### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by wafaer** [Broad-sky/common-image-segmentation-algorithms#9]
Hello, when I compile your project, I get such an error, do you know the reason, the error is as follows:
/usr/bin/ld: /home/hermione/src/test/SOLOv2-TensorRT/demo/solov2: hidden symbol `cudaMalloc' in /usr/local/cuda-11.0/lib64/libcudart_static.a(libcudart_static.a.o) is referenced by DSO
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/solov2.dir/build.make:114: /home/hermione/src/test/SOLOv2-TensorRT/demo/solov2] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/solov2.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by Broad-sky** [comment]
Hello, you can upload your CMakeLists.txt.

**Comment by Broad-sky** [comment]
> Hello, when I compile your project, I get such an error, do you know the reason, the error is as follows: /usr/bin/ld: /home/hermione/src/test/SOLOv2-TensorRT/demo/solov2: hidden symbol `cudaMalloc' in /usr/local/cuda-11.0/lib64/libcudart_static.a(libcudart_static.a.o) is referenced by DSO /usr/bin/ld: final link failed: bad value collect2: error: ld returned 1 exit status make[2]: *** [CMakeFiles/solov2.dir/build.make:114: /home/hermione/src/test/SOLOv2-TensorRT/demo/solov2] Error 1 make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/solov2.dir/all] Error 2 make: *** [Makefile:91: all] Error 2


Hello, you can upload your CMakeLists.txt.

**Comment by wafaer** [comment]
> > Hello, when I compile your project, I get such an error, do you know the reason, the error is as follows: /usr/bin/ld: /home/hermione/src/test/SOLOv2-TensorRT/demo/solov2: hidden symbol `cudaMalloc' in /usr/local/cuda-11.0/lib64/libcudart_static.a(libcudart_static.a.o) is referenced by DSO /usr/bin/ld: final link failed: bad value collect2: error: ld returned 1 exit status make[2]: *** [CMakeFiles/solov2.dir/build.make:114: /home/hermione/src/test/SOLOv2-TensorRT/demo/solov2] Error 1 make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/solov2.dir/all] Error 2 make: *** [Makefile:91: all] Error 2
> 
> Hello, you can upload your CMakeLists.txt.

Hello, thanks for your reply, here is my CMakeLists.txt:

cmake_minimum_required(VERSION 3.20)
project(SOLOv2-TensorRT)

set(CMAKE_CXX_STANDARD 14)


find_package(OpenCV 4.2.0 REQUIRED)
find_package(CUDA 11.0 REQUIRED)
set(CMAKE_PREFIX_PATH "/usr/local/lib")

set(CUDA_TOOLKIT_ROOT_DIR "/usr/local/cuda-11.0")

set(CMAKE_CUDA_COMPILER "${CUDA_TOOLKIT_ROOT_DIR}/bin/nvcc")
set(CUDA_LIB_DIR "${CUDA_TOOLKIT_ROOT_DIR}/lib64")
set(CUDA_INCLUDE "${CUDA_TOOLKIT_ROOT_DIR}/include")
set(TensorRT_LIBS nvinfer nvonnxparser nvinfer_plugin)


include_directories(${PROJECT_NAME}
${PROJECT_SOURCE_DIR}
${PROJECT_SOURCE_DIR}/include
${TensorRT_INCLUDE_DIRS}
${OpenCV_INCLUDE_DIRS}
${CUDA_INCLUDE_DIRS}
)

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/lib)

add_library(${PROJECT_NAME} SHARED
src/segmentation_trt.cpp
include/segmentation_trt.h
include/logging.h
)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/demo)

add_executable(solov2 demo/demo.cpp)
target_link_libraries(solov2 ${PROJECT_NAME} ${TensorRT_LIBS} ${OpenCV_LIBRARIES} ${CUDA_LIBRARIES})

**Comment by wafaer** [comment]
> > Hello, when I compile your project, I get such an error, do you know the reason, the error is as follows: /usr/bin/ld: /home/hermione/src/test/SOLOv2-TensorRT/demo/solov2: hidden symbol `cudaMalloc' in /usr/local/cuda-11.0/lib64/libcudart_static.a(libcudart_static.a.o) is referenced by DSO /usr/bin/ld: final link failed: bad value collect2: error: ld returned 1 exit status make[2]: *** [CMakeFiles/solov2.dir/build.make:114: /home/hermione/src/test/SOLOv2-TensorRT/demo/solov2] Error 1 make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/solov2.dir/all] Error 2 make: *** [Makefile:91: all] Error 2
> 
> Hello, you can upload your CMakeLists.txt.

I have compiled it, but the converterModel you gave cannot be used. I use ncnn to convert the ONNX file you gave to bin. Running the model on your code is wrong. How did you convert it to onnx, and can you upload the compiled code of convertModel, thank you very much.
